"""update_users

Revision ID: afc454adf306
Revises: 550fdfa00ae9
Create Date: 2025-03-09 14:05:57.938956
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'afc454adf306'
down_revision: Union[str, None] = '550fdfa00ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'password',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'password',
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
